import type { Project } from "./types";
import { coachOsShowcase } from "./showcases/coach-os";

export const additionalProjects: Project[] = [
  {
    slug: "coach-os",
    title: "CoachOS — Multi-Tenant AI SaaS Platform for Coaches, Gyms & Sports Businesses",
    shortDescription:
      "A modern multi-tenant SaaS platform for fitness coaches, gyms, academies, and sports businesses — clients, programs, nutrition, bookings, payments, and AI workflows in one system.",
    fullDescription:
      "CoachOS is a modern multi-tenant SaaS platform that enables fitness coaches, gyms, academies and sports businesses to manage clients, programs, nutrition, bookings, payments and AI-powered workflows from one platform.\n\nBuilt with enterprise-grade architecture, CoachOS spans five product lines — CoachOS, GymOS, AcademyOS, PhysioOS, and SportsOS — each with isolated tenant workspaces, branded public websites, client portals, admin dashboards, and production-ready deployment infrastructure.",
    technologies: [
      "Next.js",
      "React",
      "TypeScript",
      "Prisma",
      "PostgreSQL",
      "Better Auth",
      "Stripe",
      "Paymob",
      "Resend",
      "Redis",
      "Pusher",
      "Tailwind CSS",
      "shadcn/ui",
      "Vercel",
    ],
    category: "saas",
    segment: "enterprise-platform",
    featured: true,
    pinned: true,
    featuredOrder: 0,
    status: "production-ready",
    timeline: "2026 — Present",
    images: [],
    year: 2026,
    gradient: "from-zinc-950 via-neutral-900 to-black",
    accent: "#fafafa",
    showcase: coachOsShowcase,
    features: [
      "Multi-tenant SaaS architecture",
      "Enterprise RBAC & Better Auth",
      "Client CRM & portals",
      "Workout builder & nutrition",
      "Booking & payments (Stripe & Paymob)",
      "Marketplace & white label",
      "AI-powered workflows",
      "Admin dashboard & analytics",
      "Mobile API & custom domains",
      "Production deployment on Vercel",
    ],
    problem:
      "Fitness and sports businesses need one scalable platform to manage clients, programs, bookings, payments, and branded digital experiences — without juggling fragmented tools.",
    architecture:
      "CoachOS is engineered as a multi-tenant, API-first SaaS platform with 138+ database models, 106+ pages, 27+ REST APIs, and 60+ dashboard modules — organized across five product lines with tenant isolation, enterprise RBAC, and production deployment.",
    challenges: [
      "Designing secure multi-tenant isolation across branding, data, subscriptions, and permissions.",
      "Coordinating five product lines and 60+ dashboard modules without sacrificing maintainability.",
      "Integrating payments, AI workflows, marketplace commerce, and client portals in one architecture.",
      "Shipping a production-ready platform with reporting, analytics, and enterprise controls.",
    ],
    solutions: [
      "Built a modular multi-tenant core with Better Auth, enterprise RBAC, and isolated workspaces.",
      "Structured five product lines (CoachOS, GymOS, AcademyOS, PhysioOS, SportsOS) on shared infrastructure.",
      "Delivered client portals, admin panels, public coach websites, and 27+ REST APIs.",
      "Deployed production infrastructure with Stripe, Paymob, Redis, Pusher, and Vercel.",
    ],
    results: [
      "Production-ready multi-tenant SaaS platform with 138+ database models.",
      "106+ pages across admin, client portal, and public website surfaces.",
      "Five product lines serving coaches, gyms, academies, physiotherapy, and sports organizations.",
      "Enterprise modules, marketplace, AI features, and analytics ready for scale.",
    ],
    developmentProcess: [
      "Architecture & multi-tenancy foundation",
      "Authentication & enterprise RBAC",
      "Coach platform & client CRM",
      "Payments, marketplace & booking",
      "Enterprise modules & AI features",
      "Production deployment & optimization",
    ],
  },
  {
    slug: "oncall-business-platform",
    title: "OnCall Business Platform",
    shortDescription:
      "Professional development of business systems and web applications for multiple commercial clients.",
    fullDescription:
      "Developed as part of professional work delivering software for real businesses. This engagement focused on building, maintaining, and improving business systems and web applications across multiple client projects — from feature development and API integration to production support and deployment.",
    technologies: [
      "Next.js",
      "React",
      "TypeScript",
      "Node.js",
      "PostgreSQL",
      "Drizzle ORM",
      "REST APIs",
      "Cloudflare",
      "Vercel",
    ],
    category: "saas",
    segment: "enterprise-platform",
    featured: false,
    isClientProject: true,
    status: "completed",
    timeline: "2026",
    images: [],
    year: 2026,
    gradient: "from-slate-900 via-zinc-900 to-black",
    accent: "#e4e4e7",
    features: [
      "Full-stack web applications",
      "Business system modules",
      "REST API development",
      "Database design",
      "Authentication",
      "Production support",
      "Deployment & monitoring",
    ],
    problem:
      "Business clients needed reliable software systems maintained and extended while production issues were resolved quickly.",
    architecture:
      "Full-stack architecture using Next.js, Node.js, PostgreSQL, and API-driven modules deployed through modern cloud infrastructure.",
    challenges: [
      "Supporting multiple client projects with different business requirements.",
      "Maintaining production stability while shipping new features.",
      "Integrating backend services, databases, and deployment workflows.",
    ],
    solutions: [
      "Delivered full-stack features across client business applications.",
      "Resolved production issues and improved application reliability.",
      "Built and integrated REST APIs with structured database layers.",
    ],
    results: [
      "Production-ready features delivered across multiple business projects.",
      "Improved stability and maintainability of client systems.",
      "Ongoing support for deployment and application updates.",
    ],
  },
  {
    slug: "pet-plant",
    title: "Pet Plant",
    shortDescription:
      "Commercial website developed for a real business with product presentation and customer-focused browsing.",
    fullDescription:
      "A commercial website built for Pet Plant to present the business online with a clean, responsive interface focused on product visibility and customer engagement.",
    technologies: ["Next.js", "React", "TypeScript", "Tailwind CSS", "Responsive Design"],
    category: "e-commerce",
    segment: "commercial-website",
    featured: false,
    isClientProject: true,
    status: "completed",
    timeline: "2026",
    images: [],
    year: 2026,
    gradient: "from-emerald-950 via-green-900 to-zinc-950",
    accent: "#86efac",
    features: ["Product presentation", "Responsive layout", "Modern UI", "Fast performance"],
    problem: "The business needed a professional online presence to showcase products to customers.",
    challenges: ["Presenting products clearly on mobile and desktop.", "Delivering a fast, maintainable commercial site."],
    solutions: ["Built a responsive product-focused layout.", "Used modern front-end tooling for performance and maintainability."],
    results: ["A professional commercial web presence for the business.", "Improved product visibility for online customers."],
  },
  {
    slug: "sbco-clothes",
    title: "SBCO Clothes",
    shortDescription:
      "Commercial clothing brand website with product-focused layout and responsive design.",
    fullDescription:
      "A commercial website developed for SBCO Clothes to support brand presentation, product discovery, and a polished customer experience across devices.",
    technologies: ["Next.js", "React", "TypeScript", "Tailwind CSS"],
    category: "e-commerce",
    segment: "commercial-website",
    featured: false,
    isClientProject: true,
    status: "completed",
    timeline: "2026",
    images: [],
    year: 2026,
    gradient: "from-neutral-900 via-stone-800 to-black",
    accent: "#f5f5f5",
    features: ["Brand presentation", "Product browsing", "Responsive design", "Commercial layout"],
    problem: "The clothing brand required a modern website to present collections and strengthen its digital identity.",
    challenges: ["Balancing brand aesthetics with clear product presentation.", "Ensuring consistent experience across screen sizes."],
    solutions: ["Designed a clean commercial layout aligned with the brand.", "Implemented responsive components for mobile and desktop users."],
    results: ["A credible online storefront for the clothing brand.", "Improved accessibility of brand and product information."],
  },
  {
    slug: "swing-food",
    title: "Swing Food",
    shortDescription:
      "Food business website with menu presentation, contact flows, and mobile-friendly design.",
    fullDescription:
      "A commercial website built for Swing Food to help customers explore offerings, access business information, and interact with the brand through a responsive food-service web experience.",
    technologies: ["Next.js", "React", "TypeScript", "Tailwind CSS"],
    category: "web-app",
    segment: "commercial-website",
    featured: false,
    isClientProject: true,
    status: "completed",
    timeline: "2026",
    images: [],
    year: 2026,
    gradient: "from-orange-950 via-red-950 to-zinc-950",
    accent: "#fdba74",
    features: ["Menu presentation", "Contact information", "Responsive UI", "Fast loading"],
    problem: "The food business needed a clear digital presence for customers to discover offerings and get in touch.",
    challenges: ["Making menu and contact details easy to find on mobile.", "Keeping the site lightweight and fast."],
    solutions: ["Structured the site around menu and contact sections.", "Optimized layout and performance for mobile users."],
    results: ["A professional website supporting customer discovery.", "Improved mobile access to business information."],
  },
  {
    slug: "tashqila",
    title: "Tashqila",
    shortDescription:
      "Commercial business website with modern branding, responsive layout, and customer-focused structure.",
    fullDescription:
      "A commercial website developed for Tashqila to establish a professional online presence with structured content, responsive design, and a polished user experience.",
    technologies: ["Next.js", "React", "TypeScript", "Tailwind CSS"],
    category: "web-app",
    segment: "commercial-website",
    featured: false,
    isClientProject: true,
    status: "completed",
    timeline: "2026",
    images: [],
    year: 2026,
    gradient: "from-indigo-950 via-slate-900 to-black",
    accent: "#a5b4fc",
    features: ["Business presentation", "Responsive design", "Modern branding", "Structured content"],
    problem: "The business needed a credible website to communicate its services and brand online.",
    challenges: ["Creating a professional layout without unnecessary complexity.", "Ensuring usability across devices."],
    solutions: ["Built a clean, section-based commercial website.", "Applied responsive design patterns throughout."],
    results: ["A polished business website ready for customer-facing use.", "Clear presentation of brand and business information."],
  },
  {
    slug: "home-protection",
    title: "Home Protection",
    shortDescription:
      "Service business website designed to present offerings, build trust, and support customer inquiries.",
    fullDescription:
      "A commercial website built for Home Protection to present services, communicate value to customers, and provide a trustworthy online entry point for inquiries.",
    technologies: ["Next.js", "React", "TypeScript", "Tailwind CSS"],
    category: "web-app",
    segment: "commercial-website",
    featured: false,
    isClientProject: true,
    status: "completed",
    timeline: "2026",
    images: [],
    year: 2026,
    gradient: "from-slate-950 via-blue-950 to-black",
    accent: "#93c5fd",
    features: ["Service presentation", "Trust-focused layout", "Contact flows", "Responsive design"],
    problem: "The service business needed a professional website to explain offerings and generate customer trust.",
    challenges: ["Communicating services clearly to non-technical visitors.", "Designing for clarity and credibility."],
    solutions: ["Created a structured service-focused website.", "Used clear hierarchy and responsive layouts for accessibility."],
    results: ["A trustworthy online presence for the service business.", "Improved clarity for prospective customers."],
  },
  {
    slug: "sixty-three-perfume",
    title: "Sixty Three Perfume",
    shortDescription:
      "Perfume brand website with elegant product presentation and responsive commercial design.",
    fullDescription:
      "A commercial website developed for Sixty Three Perfume to showcase products with an elegant brand experience, responsive layout, and customer-focused presentation.",
    technologies: ["Next.js", "React", "TypeScript", "Tailwind CSS"],
    category: "e-commerce",
    segment: "commercial-website",
    featured: false,
    isClientProject: true,
    status: "completed",
    timeline: "2026",
    images: [],
    year: 2026,
    gradient: "from-zinc-900 via-amber-950 to-black",
    accent: "#fcd34d",
    features: ["Product showcase", "Elegant branding", "Responsive layout", "Commercial presentation"],
    problem: "The perfume brand needed a refined website to present products and strengthen brand perception online.",
    challenges: ["Matching premium brand positioning in the UI.", "Keeping product presentation clear on all devices."],
    solutions: ["Designed an elegant, minimal commercial layout.", "Implemented responsive product presentation patterns."],
    results: ["A premium-feeling website for the perfume brand.", "Improved online product visibility."],
  },
];

export const clientProjectsDisclaimer =
  "Additional commercial projects were delivered under company ownership and cannot be publicly disclosed.";

export const clientProjectsFootnote =
  "More commercial projects available upon request.";
