import type { ProjectShowcase } from "../types";

export const coachOsShowcase: ProjectShowcase = {
  statusBadge: "Production Ready",
  highlights: [
    "Multi-Tenant SaaS Architecture",
    "Next.js 15",
    "TypeScript",
    "Prisma ORM",
    "PostgreSQL",
    "Better Auth",
    "Enterprise RBAC",
    "AI Features",
    "Stripe & Paymob Ready",
    "Marketplace",
    "Client Portal",
    "Admin Dashboard",
    "White Label",
    "Public Coach Website",
    "Booking System",
    "Mobile API",
    "Enterprise Modules",
    "Reporting & Analytics",
    "SEO Ready",
    "Production Deployment",
  ],
  stats: [
    { value: "138+", label: "Database Models" },
    { value: "106+", label: "Pages" },
    { value: "27+", label: "REST APIs" },
    { value: "60+", label: "Dashboard Modules" },
    { value: "18+", label: "Public Website Pages" },
    { value: "11+", label: "Client Portal Pages" },
    { value: "12+", label: "Admin Pages" },
    { value: "5", label: "Product Lines" },
  ],
  productLines: ["CoachOS", "GymOS", "AcademyOS", "PhysioOS", "SportsOS"],
  featureGrid: [
    "Authentication",
    "Client CRM",
    "Workout Builder",
    "Nutrition",
    "Booking",
    "Payments",
    "Invoices",
    "Coupons",
    "Marketplace",
    "Reports",
    "Automation",
    "AI",
    "White Label",
    "Custom Domains",
    "Email",
    "Analytics",
    "Client Portal",
    "Admin Panel",
    "Enterprise",
  ],
  timelinePhases: [
    { title: "Architecture & Multi-tenancy" },
    { title: "Authentication" },
    { title: "Coach Platform" },
    { title: "Payments" },
    { title: "Marketplace" },
    { title: "Enterprise Modules" },
    { title: "Deployment" },
    { title: "Production" },
  ],
  labels: {
    highlights: "Highlights",
    statistics: "Platform Statistics",
    productLines: "Product Lines",
    techStack: "Tech Stack",
    features: "Features",
    timeline: "Development Timeline",
    gallery: "Gallery",
    viewCaseStudy: "Explore full case study",
    flagship: "Flagship SaaS",
    mockupDesktop: "Desktop dashboard",
    mockupTablet: "Tablet experience",
    mockupMobile: "Mobile client portal",
  },
};
